### ISSUE TITLE
Crashes GameLoader (ver Beta21)

### ISSUE THREAD

**Issue by Chirishman** [TEAMarg/ID-15-Shadow-Runner#2]
Attempting to upload v1.6.1 arduboy file using the latest GameLoader (v21) crashes the application.

**Comment by JO3RI** [comment]
I'll fix this when back from vacation in August :)

**Comment by Chirishman** [comment]
Additional info: The arduboy team's loader will successfully upload it but will show red error symbol afterwards.

**Comment by JO3RI** [comment]
The info.json referred to SHRUN_AB_v16.hex instead of SHRUN_AB_v161.hex. Fixed the json file and re uploaded the .arduboy file. Should work now.
